CREATE TABLE IF NOT EXISTS `Asignaturas` (
 `Id_Asignatura` INT NOT NULL AUTO_INCREMENT,
 `Nombre` VARCHAR(350) NOT NULL,
 `Cod_Interno` VARCHAR(350) NOT NULL,
 `CreateAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY(`Cod_Interno`),
 PRIMARY KEY (`Id_Asignatura`)
);

