CREATE TABLE `Silabo_Entradas` (
 `Id_Silabo` INT NOT NULL AUTO_INCREMENT,
 `Id_Ped` INT NOT NULL,
 `Id_Carrera` INT NOT NULL,
 `Id_Asignatura` INT NOT NULL,
 `Id_Grupo` INT NOT NULL,
 `Modalidad` INT NOT NULL,
 `Createat` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `Editedat` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `Createby` INT NOT NULL,
 PRIMARY KEY (`Id_Silabo`),
 CONSTRAINT FOREIGN KEY (`Id_Asignatura`) REFERENCES `Asignaturas` (`Id_Asignatura`) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT FOREIGN KEY (`Id_Carrera`) REFERENCES `Carreras` (`Id_Carrera`) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT FOREIGN KEY (`Id_Grupo`) REFERENCES `Grupos` (`Id_Grupo`) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT FOREIGN KEY (`Id_Ped`) REFERENCES `Peds` (`Id_Ped`) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT FOREIGN KEY (`Createby`) REFERENCES `User_Entries` (`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);
