CREATE TABLE IF NOT EXISTS `User_Entries` (
 `User_Id` INT AUTO_INCREMENT NOT NULL,
 `User_Type` INT NOT NULL DEFAULT '0',
 `User_Name` VARCHAR(120) NOT NULL,
 `User_Password` CHAR(32) NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Name`),
 PRIMARY KEY(`User_Id`)
);

CREATE TABLE IF NOT EXISTS `User_Details` (
 `User_Id` INT NOT NULL,
 `User_FullName` VARCHAR(120) NOT NULL,
 `User_Email` VARCHAR(255) NOT NULL,
 UNIQUE KEY(`User_Email`),
 PRIMARY KEY(`User_Id`),
 FOREIGN KEY(`User_Id`) REFERENCES `User_Entries`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `User_Sessions` (
 `User_Id` INT NOT NULL,
 `Session_IP` BINARY(16) NULL DEFAULT NULL,
 `Session_Token` CHAR(32) NOT NULL,
 `Create_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY(`User_Id`, `Session_Token`),
 FOREIGN KEY(`User_Id`) REFERENCES `User_Entries`(`User_Id`) ON UPDATE CASCADE ON DELETE CASCADE
);

